### PR TITLE
Update to Varnish 6.0.2

### PR DESCRIPTION
**Pull request by pietervogelaar**

### CODE REVIEW

**Comment by maetthu** [comment]
Thanks - I completely missed that release, there was no notification on the announce mailinglist :confused:

**Comment by pietervogelaar** [comment]
@maetthu Thanks for merging, would you make the tag 6.0.2 available on Docker hub? I see that it fails somehow https://hub.docker.com/r/emgag/varnish/builds/

**Comment by maetthu** [comment]
@pietervogelaar I'm on it, it will be available shortly - had to run some tests and update docs and Makefile as well. I stopped using the automatic build on Docker hub since it's rather slow and difficult to debug, but it looks like it's only disabled for the master branch.

**Comment by maetthu** [comment]
@pietervogelaar 6.0.2 is now available

**Comment by pietervogelaar** [comment]
@maetthu Thank you very much, works great!

**Pull request merged**
